name: Publish App
run-name: ${{github.event.head_commit.message}}
on:
  push:
    tags:
      - v*
jobs:
  get-source-code:
    name: "Get source code project"
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.upload-source.outputs.artifact-id }}
    steps:
      - name: Get source code
        uses: actions/checkout@v7
      - name: Uploads file in artifact
        uses: actions/upload-artifact@v7
        id: upload-source
        with:
          name: upload-source
          path: |
            public/
            src/
            index.html
            package.json
            package-lock.json
            vite.config.js
            nginx.conf
            eslint.config.js