name: build-project
run-name: Running build-project
on:
  push:
    tags:
      - v*
jobs:
  Build-Project:
    runs-on:  ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Build images
        run: docker build . -t ghcr.io/${{github.repository}}:latest
      - name: Login to docker
        run: echo -n ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io --username ${{github.actor}} --password-stdin
      - name: push to ghcr.io
        run: docker push ghcr.io/${{github.repository}}:latest



